name: Build and Deploy
on:
  push:
    branches: [staging]
  pull_request:
    branches: [staging]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "badging-staging"
          heroku_email: "ekaxada@gmail.com"
